### ISSUE TITLE
Hey, I am interested in this content

### ISSUE THREAD

**Issue by typedefstructer** [bbengfort/replicated-storage-systems#1]
any plans on updating it.
And can you point me to some beginner resources?

**Comment by bbengfort** [comment]
Huh, I had forgotten about this - you could checkout:

https://jacobmartins.com/2017/01/29/practical-golang-building-a-simple-distributed-one-value-database-with-hashicorp-serf/

As a simple start.

**Comment by typedefstructer** [comment]
Thanks a lot
